### ISSUE TITLE
SDS - Software Design Specification 

### ISSUE THREAD

**Issue by mazmaz2k** [mazmaz2k/jlm.fm#16]
Todo:
#### Related Issues/Tasks
- [x] #8 UML
- [x] #9 State Charts
- [x] #10 Main page
- [x] #11 CRC
- [x] #12 User Manual
- [x] #13 Non-functional requirements
- [x] #14 Initial Test Plan
- [x] #15 Capabilities - update risk management

#### Scenario (test)
- [x] Step 1-We had common dependencies 
- [x] Step 2 -We divided our workload
- [x] Expected result -Completed app design

## User Story Template
- As a app developer
- I want to know what is my design before develop my app 
- So that there is no questions about the design .

#### Expected behavior
Different files containing the design of the app, the design should contain all the page of the app.

**Comment by mazmaz2k** [comment]
finish SDS @robi-y @kob-e 
here is the page [SDS](https://github.com/mazmaz2k/jlm.fm/wiki/SDS#sds)

**Comment by mazmaz2k** [comment]
#7

**Comment by mazmaz2k** [comment]
#

**Comment by mazmaz2k** [comment]
ZFR  #7
