### ISSUE TITLE
ZFR Submission

### ISSUE THREAD

**Issue by mazmaz2k** [mazmaz2k/jlm.fm#7]
TODO issues:
- [x] #1  Add event to my app
- [x] #4   finish srs
- [x] #5   add slide show
- [x] #6  Present app to users

#### Need To Do (ZFR HW 3)
- [x] Work stages
- [x] Version Control
- [x] Prototype- omri
- [x] Product documentation - doron
- [x]  review ZFR - alex
- [x]  iteration 1

## User Story Template
- As a ...
- I want ...
- So that ...

#### Checklist, e.g.,:
- [x] Feature scenarios/tests passing
- [x] Iteration page updated, including:
  - [x] Iteration retrospective
  - [x] Code reviewes
  - [ ] Client review
  - [x] Issues updates
  - [x] Section on application of course materials
- [x] git tag
- [x] Next iteration:
  - [x] Open page
  - [x] Select stories and plan issues
  - [x] Test scenarios
- [x] All engineers filled peer-review 
- [x] Submitted
  - [x] Announcement in chat room
  - [x] Assign this issue to checker
  - [x] Register for a review meeting

**Comment by mazmaz2k** [comment]
all is done @kob-e .
here is the link to [ZFR](https://github.com/mazmaz2k/jlm.fm/wiki/Iteration-0-ZFR#Iteration-0-ZFR)

**Comment by mazmaz2k** [comment]

